/**
 * Source file for the LevelController model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "LevelController.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace LevelController { 

LevelController::LevelController(ChannelOut<double> *in, ChannelIn<double> *out) :
    Sequential(NULL)
{
  SETNAME(this, "LevelController");

  // Initialize model objects
  myFMI_LevelController = new FMI_LevelController::FMI_LevelController(v_in, v_out);
  SETNAME(myFMI_LevelController, "FMI_LevelController");
  myr_in = new Reader<double>(&v_in, in);
  SETNAME(myr_in, "r_in");
  myw_out = new Writer<double>(&v_out, out);
  SETNAME(myw_out, "w_out");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myw_out,
    (CSPConstruct *) myr_in,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");


  // Register model objects
  this->append_child(myFMI_LevelController);
  this->append_child(myPARALLEL);

  // protected region constructor on begin
  // protected region constructor end
}

LevelController::~LevelController()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myw_out;
  delete myr_in;
  delete myFMI_LevelController;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
