# build.mk file for plant.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=lib/libplant.a

plant/lib/libplant.a:
	@echo
	@echo "Building $@"
	@make -C plant --no-print-directory

lib/libplant.a: plant/lib/libplant.a | lib
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that lib/libplant.a gets properly rebuild
plant/lib/libplant.a: plant/src/plant.cpp plant/include/plant/plant.h
plant/lib/libplant.a: plant/src/FMI_plant.cpp plant/include/plant/FMI_plant.h plant/include/plant/fmi2Functions.h plant/include/plant/logger.h

# protected region additional dependencies on begin
# protected region additional dependencies end