/**
 * Header file for the LevelController model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "FMI_LevelController.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace LevelController { 

class LevelController : public Sequential
{

public:
  // Define constructor and destructor
  LevelController(ChannelOut<double> *in, ChannelIn<double> *out);
  virtual ~LevelController();

private:

  // Class variables
  double v_in;
  double v_out;
  fmi2FMUstate v_FMUstate;

  // Model objects
  FMI_LevelController::FMI_LevelController *myFMI_LevelController;
  Reader<double> *myr_in;
  Writer<double> *myw_out;

  // Model groups
  Parallel *myPARALLEL;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
