/**
 * Source file for the MainModel model
 * Generated by the TERRA Arch2LUNA generator version 1.0.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 

MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize channels
  myLevelControllerout_to_plantcontrolChannel = new UnbufferedChannel<double, One2In, Out2One>();
  myplantheight_to_LevelControllerinChannel = new UnbufferedChannel<double, One2In, Out2One>();

  // Initialize model objects
  myLevelController = new LevelController::LevelController(myplantheight_to_LevelControllerinChannel, myLevelControllerout_to_plantcontrolChannel);
  SETNAME(myLevelController, "LevelController");
  myplant = new plant::plant(myLevelControllerout_to_plantcontrolChannel, myplantheight_to_LevelControllerinChannel);
  SETNAME(myplant, "plant");

  // Create Parallel group containing all architecture components
  parallelGroup = new Parallel(
    (CSPConstruct *) myLevelController,
    (CSPConstruct *) myplant,
    NULL
  );
  SETNAME(parallelGroup, "parallelGroup");

  // Register group as top-level recursive object
  setToActivate(parallelGroup);
  setEvaluateCondition(true);
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // Destroy model objects
  delete myplant;
  delete myLevelController;

  // Destroy channels
  delete myLevelControllerout_to_plantcontrolChannel;
  delete myplantheight_to_LevelControllerinChannel;
}

// Close namespace(s)
} 
