# build.mk file for FluidLevelControl.archm, provide information to 'project MakeFile' 
# Generated by the TERRA Arch2LUNA generator version 1.0.1
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/FluidLevelControl

FluidLevelControl/FluidLevelControl:
	@echo
	@echo "Building $@"
	@make -C FluidLevelControl --no-print-directory

bin/FluidLevelControl: FluidLevelControl/FluidLevelControl | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/FluidLevelControl gets properly rebuild
FluidLevelControl/FluidLevelControl: FluidLevelControl/src/main.cpp LevelController/lib/libLevelController.a plant/lib/libplant.a
FluidLevelControl/FluidLevelControl: FluidLevelControl/src/MainModel.cpp FluidLevelControl/include/MainModel.h LevelController/include/LevelController/LevelController.h plant/include/plant/plant.h

# protected region additional dependencies on begin
# protected region additional dependencies end