/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  plant
 *  model: FluidLevelControl_Modified
 *  expmt: FluidLevelControl_Modified
 *  date:  July 3, 2017
 *  time:  6:09:05 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.6 Campus Licentie
 *  build: 4.6.3.7733
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
void XXInitializeSubmodel (xx_ModelInstance* model_instance);
void XXCalculateSubmodel (xx_ModelInstance* model_instance, XXDouble t);
void XXTerminateSubmodel (xx_ModelInstance* model_instance, XXDouble t);

#endif

