/**
 * Source file for the plant model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "plant.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace plant { 

plant::plant(ChannelOut<double> *control, ChannelIn<double> *height) :
    Sequential(NULL)
{
  SETNAME(this, "plant");

  // Initialize model objects
  myFMI_plant = new FMI_plant::FMI_plant(v_control, v_height);
  SETNAME(myFMI_plant, "FMI_plant");
  myr_control = new Reader<double>(&v_control, control);
  SETNAME(myr_control, "r_control");
  myw_height = new Writer<double>(&v_height, height);
  SETNAME(myw_height, "w_height");

  // Create IO group
  myIO = new Parallel(
    (CSPConstruct *) myr_control,
    (CSPConstruct *) myw_height,
    NULL
  );
  SETNAME(myIO, "IO");


  // Register model objects
  this->append_child(myFMI_plant);
  this->append_child(myIO);

  // protected region constructor on begin
  // protected region constructor end
}

plant::~plant()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin
  // protected region destructor end

  // Destroy model groups
  delete myIO;

  // Destroy model objects
  delete myw_height;
  delete myr_control;
  delete myFMI_plant;
}



// protected region additional functions on begin
// protected region additional functions end

// Close namespace(s)
} 
